### ISSUE TITLE
Bazaar does not install

### ISSUE THREAD

**Issue by Ralkage** [andreherberth/pockethold#22]
v0.1.0-beta.2

With this version, I have tested locally as well as on shared hosting and Bazaar does not install after the button is clicked. It is missing from the extensions page after the final installation phase.

**Comment by andreherberth** [comment]
Hi, thanks for submitting the bug. I am currently on vacation, and I will not be able to dig into the code just yet. I expect to be home on Sunday. 

That said. I did not initially manage to reproduce the problem, alas, I decided to try under a different environment, which I believe reproduced it. This is the error I got: 

```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - Installation request for doctrine/inflector (locked at v1.2.0) -> satisfiable by doctrine/inflector[v1.2.0].

Installation failed, reverting ./composer.json to its original content ``
```

@luceos - Since I am not home atm I can't verify, but, is the above only in require-dev?
