### ISSUE TITLE
not downloading and not installing stuck at step 1

### ISSUE THREAD

**Issue by Brabus453** [andreherberth/pockethold#43]
hi

it is not downloading and not installing stuck at step 1

when you click step one download, there current task log is showing, then, back to step 1 download button...

**Comment by andreherberth** [comment]
Hi @Brabus453 I am so sorry it took me 4 days to answer this one. 
Alas, I am fairly sure that this issue must be caused by folder permissions, ie, the web user was not allowed to write the needed progress and log files to continue. 

The way the client works is that if taskname.start/done is not present, it reverts to previous stage where a taskname.start/done is found. So, if it reverts back to step1 download button, it could not write the first .start file, and thus, redirect you back.

**Comment by ghost** [comment]
@Brabus453 , have you tried the solution I outlined in [issue #45 ](https://github.com/Pockethold/pockethold/issues/45)?
