### ISSUE TITLE
Permission error and missing file during installation

### ISSUE THREAD

**Issue by ghost** [andreherberth/pockethold#45]
After uploading installer.php + pockethold folder to server, I was stuck on step 1, and received a 500 error.

**Output from apache error log**
`[Tue Mar 05 11:32:39.109649 2019] [php7:warn] [pid 19699] [client 192.168.0.3:51517] PHP Warning:  file_put_contents(/var/www/html/flarum/pockethold/log/ajax.log): failed to open stream: No such file or directory in /var/www/html/flarum/pockethold/classes/pockethold.class.php on line 41, referer: http://192.168.0.19/flarum/installer.php`

This was resolved with manually creating the ajax.log in pockethold/log/ajax.log

OS: Debian 8

EDIT: Changed title to better reflect issue

**Comment by 4yx** [comment]
Thank you so much for this!
I had set both installer.php and all files in the "pockethold" directory permissions to 777, however I was still getting this error, creating the file and setting permissions for it fixed it.

Perhaps the developers should have a look at this?

EDIT:
Turns out that, if a log/ajax.log file is present in the Pockethold directory, even without setting permissions, the installer works (at least for me).
Does it work for anyone else without setting the permissions?

**Comment by tobyworks** [comment]
@PCTipsGR Yes, this fixes the issue

**Comment by andreherberth** [comment]
One should never use 777 as permission on files/folders on a publicly facing web server. Alas, something is blocking Ajax.log from being created. I am looking into it, but it would be nice if anyone had a php error log from a case this happens.

**Comment by ghost** [comment]
Here is an excerpt from the file error_log from a fresh install, where the same issue was encountered.

`[11-Jul-2019 22:46:39 Europe/Berlin] PHP Warning:  file_put_contents(/public_html/pockethold/log/ajax.log): failed to open stream: No such file or directory in /public_html/pockethold/classes/pockethold.class.php on line 41
`
[Full error_log](https://pastebin.com/Tf4Wpqw5)

Manually creating the directory **/log/** containing the file **ajax.log** solved the issue.
